package com.adil.routes.draw.models.common

enum class FrameType {
    TYPE_CHAT_MESSAGE,
    TYPE_DRAW_DATA,
    TYPE_ANNOUNCEMENT,
    TYPE_GAME_ERROR,
    TYPE_JOIN_ROOM_HANDSHAKE,
    TYPE_PHASE_CHANGE,
    TYPE_CHOSEN_WORD,
    TYPE_GAME_STATE,
    TYPE_NEW_WORDS,
    TYPE_PLAYERS_LIST,
    TYPE_PING,
    TYPE_DISCONNECT_REQUEST,
    TYPE_DRAW_ACTION,
    TYPE_CUR_ROUND_DRAW_INFO,
}